// Crypto Comparison pages — SEO long-tail "X vs Y" pages generated by GPT-5.4
//
// Public:
//   GET /api/v1/compare           → { ok, count, items:[{slug,title,a,b}] }
//   GET /api/v1/compare/:slug     → { ok, item:{...} }
//
// Admin:
//   POST /api/v1/admin/compare/generate body:{ pairs:[["bitcoin","ethereum"],...] }
//   GET  /api/v1/admin/compare/status

import path from 'path';
import { generateJSON, loadJSON, saveJSON, slugify, SEO_DATA_DIR } from './_seo_generator.js';

const FILE = path.join(SEO_DATA_DIR, 'comparisons.json');

// 50 most-searched crypto comparisons (FR-speaking market)
const DEFAULT_PAIRS = [
  ['Bitcoin', 'Ethereum'], ['Solana', 'Ethereum'], ['Cardano', 'Solana'],
  ['Bitcoin', 'Litecoin'], ['Avalanche', 'Solana'], ['Polkadot', 'Cosmos'],
  ['Chainlink', 'Band Protocol'], ['Uniswap', 'PancakeSwap'], ['Aave', 'Compound'],
  ['USDT', 'USDC'], ['DAI', 'USDC'], ['Polygon', 'Arbitrum'],
  ['Arbitrum', 'Optimism'], ['Base', 'Arbitrum'], ['BNB', 'Ethereum'],
  ['XRP', 'Stellar'], ['Bitcoin', 'Bitcoin Cash'], ['Ethereum Classic', 'Ethereum'],
  ['Dogecoin', 'Shiba Inu'], ['Monero', 'Zcash'], ['Tezos', 'Algorand'],
  ['Near', 'Aptos'], ['Sui', 'Aptos'], ['Filecoin', 'Arweave'],
  ['Render', 'Akash'], ['Fetch.ai', 'SingularityNET'], ['Injective', 'dYdX'],
  ['GMX', 'dYdX'], ['Curve', 'Uniswap'], ['Lido', 'Rocket Pool'],
  ['Coinbase', 'Binance'], ['Kraken', 'Binance'], ['Bybit', 'OKX'],
  ['MetaMask', 'Trust Wallet'], ['Ledger', 'Trezor'], ['Phantom', 'Solflare'],
  ['Trading spot', 'Trading futures'], ['DCA', 'Lump sum'],
  ['Staking', 'Yield farming'], ['Holding', 'Trading actif'],
  ['Hot wallet', 'Cold wallet'], ['DEX', 'CEX'],
  ['ICO', 'IDO'], ['Airdrop', 'Yield farming'],
  ['Bitcoin', 'Or'], ['Crypto', 'Actions bourse'],
];

async function generateOne(a, b) {
  const systemPrompt = `Tu écris un article SEO comparatif crypto en français pour cryptoia.ca.
Style : objectif, équilibré, avec des données chiffrées concrètes. Pas de FUD ni de hype.
Réponds UNIQUEMENT en JSON valide:
{
  "title": "${a} vs ${b} : comparatif complet 2026",
  "meta_description": "1-2 phrases (max 160 chars) optimisées pour le CTR Google",
  "intro": "Paragraphe d'accroche en markdown (~150 mots) qui pose la question et résume le verdict",
  "criteria": [
    {"name": "Cas d'usage", "a": "...", "b": "...", "winner": "${a}|${b}|égalité"},
    {"name": "Technologie / Consensus", "a": "...", "b": "...", "winner": "..."},
    {"name": "Vitesse de transaction", "a": "...", "b": "...", "winner": "..."},
    {"name": "Frais", "a": "...", "b": "...", "winner": "..."},
    {"name": "Décentralisation / Sécurité", "a": "...", "b": "...", "winner": "..."},
    {"name": "Écosystème & adoption", "a": "...", "b": "...", "winner": "..."},
    {"name": "Performance / ROI historique", "a": "...", "b": "...", "winner": "..."}
  ],
  "verdict": "Conclusion en markdown (~150 mots) qui répond clairement à 'lequel choisir selon ton profil ?' (trader court terme, holder long terme, débutant)",
  "faq": [
    {"q": "Peut-on détenir les deux ?", "a": "..."},
    {"q": "Lequel est plus risqué ?", "a": "..."},
    {"q": "Lequel pour débuter ?", "a": "..."}
  ]
}`;
  const userPrompt = `Compare ${a} vs ${b}.`;
  return await generateJSON({ systemPrompt, userPrompt, maxTokens: 3200 });
}

export default function registerCompareRoutes(app, { requireAdmin } = {}) {
  const adminGuard = requireAdmin || ((_req, _res, next) => next());

  app.get('/api/v1/compare', (_req, res) => {
    const db = loadJSON(FILE, { items: [] });
    const items = (db.items || []).map(i => ({ slug: i.slug, title: i.title, a: i.a, b: i.b }));
    res.json({ ok: true, count: items.length, items });
  });

  app.get('/api/v1/compare/:slug', (req, res) => {
    const db = loadJSON(FILE, { items: [] });
    const item = (db.items || []).find(i => i.slug === req.params.slug);
    if (!item) return res.status(404).json({ ok: false, error: 'not_found' });
    res.json({ ok: true, item });
  });

  app.post('/api/v1/admin/compare/generate', adminGuard, async (req, res) => {
    if (!process.env.EMERGENT_LLM_KEY) return res.status(503).json({ ok: false, error: 'EMERGENT_LLM_KEY missing' });
    const pairs = Array.isArray(req.body?.pairs) && req.body.pairs.length > 0
      ? req.body.pairs
      : DEFAULT_PAIRS;
    const batchSize = Math.min(parseInt(req.body?.batch_size) || 5, 5);
    const db = loadJSON(FILE, { items: [] });
    const existing = new Set(db.items.map(i => i.slug));
    const toProcess = pairs.filter(([a, b]) => !existing.has(slugify(`${a}-vs-${b}`))).slice(0, batchSize);
    if (toProcess.length === 0) {
      return res.json({ ok: true, added: 0, message: 'All requested pairs already exist', total: db.items.length });
    }
    const added = [];
    for (const [a, b] of toProcess) {
      try {
        const gen = await generateOne(a, b);
        const slug = slugify(`${a}-vs-${b}`);
        if (existing.has(slug)) continue;
        db.items.push({
          slug, a, b,
          title: gen.title || `${a} vs ${b}`,
          meta_description: gen.meta_description || '',
          intro: gen.intro || '',
          criteria: Array.isArray(gen.criteria) ? gen.criteria : [],
          verdict: gen.verdict || '',
          faq: Array.isArray(gen.faq) ? gen.faq.slice(0, 6) : [],
          generatedAt: new Date().toISOString(),
        });
        existing.add(slug);
        added.push({ slug, title: gen.title });
      } catch (e) {
        console.error(`[Compare] gen failed for ${a}/${b}:`, e?.message);
      }
    }
    saveJSON(FILE, db);
    res.json({ ok: true, added: added.length, total: db.items.length, items: added });
  });

  app.get('/api/v1/admin/compare/status', adminGuard, (_req, res) => {
    const db = loadJSON(FILE, { items: [] });
    const existing = new Set(db.items.map(i => i.slug));
    const remaining = DEFAULT_PAIRS.filter(([a, b]) => !existing.has(slugify(`${a}-vs-${b}`)));
    res.json({
      ok: true,
      total: db.items.length,
      default_pool: DEFAULT_PAIRS.length,
      remaining_default: remaining.length,
      remaining_pairs: remaining.slice(0, 10),
      has_llm_key: !!process.env.EMERGENT_LLM_KEY,
    });
  });

  console.log('[Compare] ✅ Routes registered (/api/v1/compare/* + /api/v1/admin/compare/*)');
}
