// SEO Glossary page — /lexique (list) + /lexique/:slug (detail)
// Loads from /api/v1/glossary (generated by the GPT-5.4 backend)
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import { BookOpen, Search, ArrowRight, ArrowLeft, HelpCircle } from "lucide-react";

type GlossaryItem = {
  slug: string;
  title: string;
  short: string;
  content?: string;
  related?: string[];
  faq?: { q: string; a: string }[];
};

export default function Glossary() {
  const { slug } = useParams<{ slug?: string }>();

  if (slug) return <GlossaryDetail slug={slug} />;
  return <GlossaryList />;
}

function GlossaryList() {
  const [items, setItems] = useState<GlossaryItem[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/v1/glossary").then(r => r.json()).then((d) => {
      if (d?.ok) setItems(d.items || []);
      setLoading(false);
    }).catch(() => setLoading(false));
    document.title = "Lexique Crypto — CryptoIA";
  }, []);

  const filtered = items.filter(i => i.title.toLowerCase().includes(query.toLowerCase()) || i.short?.toLowerCase().includes(query.toLowerCase()));
  // Group by first letter
  const groups: Record<string, GlossaryItem[]> = {};
  for (const it of filtered) {
    const letter = it.title.charAt(0).toUpperCase();
    (groups[letter] = groups[letter] || []).push(it);
  }
  const letters = Object.keys(groups).sort();

  return (
    <div className="flex min-h-screen bg-[#0a0e1a] text-white">
      <Sidebar />
      <main className="flex-1 px-6 py-10 max-w-5xl mx-auto" data-testid="glossary-list">
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/30 mb-4">
            <BookOpen className="w-3.5 h-3.5 text-indigo-300" />
            <span className="text-[11px] uppercase tracking-widest font-black text-indigo-300">Glossaire</span>
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black mb-3 bg-gradient-to-r from-indigo-300 via-purple-300 to-pink-300 bg-clip-text text-transparent">
            Lexique Crypto
          </h1>
          <p className="text-base text-gray-400 max-w-2xl mx-auto">{items.length} termes essentiels expliqués clairement, pour débuter ou approfondir tes connaissances crypto.</p>
        </div>
        <div className="relative mb-6">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
          <input
            value={query} onChange={(e) => setQuery(e.target.value)}
            placeholder="Rechercher un terme…"
            data-testid="glossary-search"
            className="w-full pl-10 pr-3 py-3 rounded-xl bg-white/[0.05] border border-white/[0.08] text-sm focus:border-indigo-500/50 focus:outline-none"
          />
        </div>
        {loading && <p className="text-center text-gray-500 py-12">Chargement…</p>}
        {!loading && items.length === 0 && (
          <p className="text-center text-gray-500 py-12" data-testid="glossary-empty">
            Le glossaire sera bientôt disponible. <Link to="/admin/seo-content" className="text-indigo-400 hover:underline">Admin : générer le glossaire →</Link>
          </p>
        )}
        {letters.map(letter => (
          <div key={letter} className="mb-8" data-testid={`glossary-letter-${letter}`}>
            <h2 className="text-2xl font-black text-indigo-300 mb-3">{letter}</h2>
            <div className="grid md:grid-cols-2 gap-3">
              {groups[letter].map(item => (
                <Link key={item.slug} to={`/lexique/${item.slug}`} data-testid={`glossary-item-${item.slug}`}
                  className="group rounded-xl border border-white/[0.06] bg-white/[0.02] hover:bg-white/[0.04] hover:border-indigo-500/30 transition-all p-4">
                  <h3 className="text-base font-bold text-white group-hover:text-indigo-200 transition-colors flex items-center justify-between gap-2">
                    {item.title}
                    <ArrowRight className="w-3.5 h-3.5 text-gray-500 group-hover:text-indigo-400 group-hover:translate-x-0.5 transition-transform" />
                  </h3>
                  {item.short && <p className="text-xs text-gray-400 mt-1.5 line-clamp-2">{item.short}</p>}
                </Link>
              ))}
            </div>
          </div>
        ))}
        <Footer />
      </main>
    </div>
  );
}

function GlossaryDetail({ slug }: { slug: string }) {
  const [item, setItem] = useState<GlossaryItem | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    fetch(`/api/v1/glossary/${slug}`).then(r => {
      if (r.status === 404) { setNotFound(true); setLoading(false); return null; }
      return r.json();
    }).then((d) => {
      if (d?.ok) { setItem(d.item); document.title = `${d.item.title} — Lexique CryptoIA`; }
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [slug]);

  return (
    <div className="flex min-h-screen bg-[#0a0e1a] text-white">
      <Sidebar />
      <main className="flex-1 px-6 py-10 max-w-3xl mx-auto" data-testid="glossary-detail">
        <Link to="/lexique" className="inline-flex items-center gap-1 text-sm text-indigo-400 hover:text-indigo-300 mb-6"><ArrowLeft className="w-4 h-4" /> Tous les termes</Link>
        {loading && <p className="text-center text-gray-500 py-12">Chargement…</p>}
        {notFound && <p className="text-center text-gray-500 py-12" data-testid="glossary-not-found">Terme introuvable.</p>}
        {item && (
          <article className="prose prose-invert max-w-none">
            <h1 className="text-4xl font-black mb-2 bg-gradient-to-r from-indigo-300 to-purple-300 bg-clip-text text-transparent">{item.title}</h1>
            {item.short && <p className="text-base text-gray-300 leading-relaxed border-l-2 border-indigo-500/50 pl-4 italic">{item.short}</p>}
            {item.content && <div className="mt-6 text-gray-300 leading-relaxed whitespace-pre-wrap" dangerouslySetInnerHTML={{ __html: markdownToHtml(item.content) }} />}
            {item.related && item.related.length > 0 && (
              <div className="mt-10 not-prose">
                <h3 className="text-sm uppercase tracking-wider text-gray-400 font-black mb-3">Termes connexes</h3>
                <div className="flex flex-wrap gap-2">
                  {item.related.map((r, i) => (
                    <Link key={i} to={`/lexique/${slugify(r)}`} className="px-3 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-xs font-bold text-indigo-300 hover:bg-indigo-500/20 transition-colors">
                      {r}
                    </Link>
                  ))}
                </div>
              </div>
            )}
            {item.faq && item.faq.length > 0 && (
              <div className="mt-10 not-prose">
                <h3 className="text-sm uppercase tracking-wider text-gray-400 font-black mb-3 flex items-center gap-2"><HelpCircle className="w-4 h-4" /> Questions fréquentes</h3>
                <div className="space-y-3">
                  {item.faq.map((f, i) => (
                    <div key={i} className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4">
                      <p className="font-bold text-white mb-2">{f.q}</p>
                      <p className="text-sm text-gray-300 leading-relaxed">{f.a}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </article>
        )}
        <Footer />
      </main>
    </div>
  );
}

// Lightweight markdown → HTML (h2, h3, lists, bold, italic, paragraphs)
function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.*)$/gm, '<h3 class="text-lg font-black mt-6 mb-2 text-white">$1</h3>')
    .replace(/^## (.*)$/gm, '<h2 class="text-xl font-black mt-8 mb-3 text-indigo-200">$1</h2>')
    .replace(/^- (.*)$/gm, '<li class="ml-4 list-disc">$1</li>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-white">$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/\n\n/g, '</p><p class="mt-4">')
    .replace(/^(?!<[hl])(.+)$/gm, '$1')
    .replace(/^/, '<p>')
    .concat('</p>');
}

function slugify(s: string) {
  return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}
