// Top cryptos pour les pages SEO /prediction/:cryptoId
export const SEO_CRYPTOS = [
  { id: "bitcoin", name: "Bitcoin", symbol: "BTC" },
  { id: "ethereum", name: "Ethereum", symbol: "ETH" },
  { id: "solana", name: "Solana", symbol: "SOL" },
  { id: "binancecoin", name: "BNB", symbol: "BNB" },
  { id: "ripple", name: "XRP", symbol: "XRP" },
  { id: "cardano", name: "Cardano", symbol: "ADA" },
  { id: "dogecoin", name: "Dogecoin", symbol: "DOGE" },
  { id: "avalanche-2", name: "Avalanche", symbol: "AVAX" },
  { id: "polkadot", name: "Polkadot", symbol: "DOT" },
  { id: "chainlink", name: "Chainlink", symbol: "LINK" },
  { id: "matic-network", name: "Polygon", symbol: "MATIC" },
  { id: "litecoin", name: "Litecoin", symbol: "LTC" },
  { id: "uniswap", name: "Uniswap", symbol: "UNI" },
  { id: "stellar", name: "Stellar", symbol: "XLM" },
  { id: "cosmos", name: "Cosmos", symbol: "ATOM" },
  { id: "algorand", name: "Algorand", symbol: "ALGO" },
  { id: "vechain", name: "VeChain", symbol: "VET" },
  { id: "fantom", name: "Fantom", symbol: "FTM" },
  { id: "tron", name: "Tron", symbol: "TRX" },
  { id: "near", name: "NEAR Protocol", symbol: "NEAR" },
  { id: "sui", name: "Sui", symbol: "SUI" },
  { id: "aptos", name: "Aptos", symbol: "APT" },
  { id: "arbitrum", name: "Arbitrum", symbol: "ARB" },
  { id: "optimism", name: "Optimism", symbol: "OP" },
  { id: "injective-protocol", name: "Injective", symbol: "INJ" },
  { id: "hedera-hashgraph", name: "Hedera", symbol: "HBAR" },
  { id: "aave", name: "Aave", symbol: "AAVE" },
  { id: "the-graph", name: "The Graph", symbol: "GRT" },
  { id: "render-token", name: "Render", symbol: "RNDR" },
  { id: "pepe", name: "Pepe", symbol: "PEPE" },
];
